### ISSUE TITLE
Release current main branch to a new release version

### ISSUE THREAD

**Issue by 25077667** [serge1/ELFIO#124]
Hello,

I'm currently utilizing your impressive repository and have found it to be quite useful.

I've been using the latest release, "Release_3.11," and I've noticed that it generates a significant number of compilation warnings when paired with gcc 13.2.1. However, I've found that the main branch, which can be found at https://github.com/serge1/ELFIO/commit/8ae6cec5d60495822ecd57d736f66149da9b1830, works perfectly fine for me.

I'm curious if you have plans to create a new version based on the changes made in https://github.com/serge1/ELFIO/commit/8ae6cec5d60495822ecd57d736f66149da9b1830? This would be greatly appreciated.

**Comment by serge1** [comment]
Hi, it will be not a problem to generate a new release.
I'm wondering what kind of warnings do you get with 3.11. What compilation options do you use?

**Comment by 25077667** [comment]
➜  build git:(Release_3.11) gcc --version;cmake .. -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror -pedantic"
gcc (GCC) 13.2.1 20230801
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (0.3s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/ELFIO/build
➜  build git:(Release_3.11)

**Comment by 25077667** [comment]
@serge1 May I inquire about the challenges you're currently facing? I would be glad to assist you by submitting a pull request to your repository to help address these issues.

**Comment by 25077667** [comment]
@serge1 Hello, is there any progress?

**Comment by serge1** [comment]
Hi, I'll try to make a new release at this weekend

**Comment by serge1** [comment]
The new release is available at https://github.com/serge1/ELFIO/releases/tag/Release_3.12
