### ISSUE TITLE
GPL file in project

### ISSUE THREAD

**Issue by stsoe** [serge1/ELFIO#128]
Thank you for a great library.

I would like to leverage ELFIO as a submodule in my project, however, a scan of ELFIO picks up one GPL licensed files `tests/elf_examples/ls`.  I wonder if this is intentional or a mistake?  

% strings tests/elf_examples/ls |grep -i gpl
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.

**Comment by serge1** [comment]
Hi, files located in `test` directory are used for the library verification. They are not mandatory part of the library and are used during the library development only.
Specifically, `ls` executable file was added historically and is not required even for the tests. So, I have removed it from the repository in commit eb68829.
Thank you
