### ISSUE TITLE
Loading elf from buffer

### ISSUE THREAD

**Issue by georgemoralis** [serge1/ELFIO#129]
For example  [https://www.psdevwiki.com/ps4/SELF_File_Format](url) SELF files contains elf in a specific offset , so loading from buffer might be useful for these cases .

**Comment by serge1** [comment]
Please have a look at `elfio::set_address_translation()` and `address_translator` class.
The API permits address transformation for loading from a buffer at arbitrary offset.

Is it what you are looking for?

**Comment by georgemoralis** [comment]
hmm that might do the trick ,will check and tell you :)

**Comment by serge1** [comment]
Have you had a chance to check?

**Comment by georgemoralis** [comment]
not yet actually but i am adding some ps4 specific elf stuff in elfio
[](https://github.com/shadps4-emu/ext-ELFIO)
