### ISSUE TITLE
how to add from_to_host and write_to_host symbol 

### ISSUE THREAD

**Issue by xusq123** [serge1/ELFIO#141]

**Comment by serge1** [comment]
I am sorry. I don't understand your question. Can you explain more please?

**Comment by xusq123** [comment]
> I am sorry. I don't understand your question. Can you explain more please?

？？？ from_host and write to host is a std ELF ,how to add these two symbol,

**Comment by serge1** [comment]
The ELF standard does not define any symbols or section names called 'from_host' or 'write_to_host'.
Please send me a reference, an example or a description of what your intention is.

**Comment by serge1** [comment]
Is there more information available? If not, I am going to close this issue

**Comment by xusq123** [comment]
because now I am run force_riscv（which has use ELFIO ）,its ELF file not same as spike std elf (which has from host and to host to stop sim)，this github is not official github？

**Comment by serge1** [comment]
I feel that the question is not related to ELFIO library. Therefore, I am closing this issue.
Please reopen and provide more information if you feel otherwise.
