### ISSUE TITLE
arm so file saving is failed

### ISSUE THREAD

**Issue by pcheng74** [serge1/ELFIO#19]
Hi,

I have one so file which is built for arm Linux. when I tried to use elfio to parse it and save it as the new file.  Internal function layout_segments_and_their_sections will return error.

The code is simple and is like:
elf_file.load(inFilename);
elf_file.save(outFilename);

I did not do other changes.  Could you please check this issue?
[libaes.zip](https://github.com/serge1/ELFIO/files/1403855/libaes.zip)

**Comment by joy4eg** [comment]
I'm have the same issue on my amd64.

The code is pretty simple:
```c++
reader.load("my_elf");
reader.save("my_elf_out");
```
It stuck here: https://github.com/serge1/ELFIO/blob/master/elfio/elfio.hpp#L717

@serge1 any thoughts ?

**Comment by belissent** [comment]
I have an issue that might be similar on an ELF file built with the Windriver compiler

readelf on the ELF file gives the following sections (extract):
```
  [Nr] Nom               Type            Adr      Décala.Taille ES Fan LN Inf Al
...
  [12] .text             PROGBITS        00100a48 000e40 003130 00  AX  0   0  4
  [13] .sdata2           NULL            00103b78 003f70 000000 00   A  0   0  0
  [14] .rodata           PROGBITS        00103b78 003f70 000ac4 00   A  0   0  4
  [15] .sdata            NULL            21200000 004a34 000000 00   A  0   0  0
  [16] .sbss             NULL            21200000 004a34 000000 00  WA  0   0  0
  [17] .data             PROGBITS        21200000 004a34 000004 00  WA  0   0  4
  [18] .bss              NOBITS          21200004 004a38 001184 00  WA  0   0  4
...
```

And the following segments (extract):
```
  Type           Décalage Adr. vir.  Adr.phys.  T.Fich. T.Mém.  Fan Alignement
...
  LOAD           0x000000 0x2204a200 0x00000000 0x00000 0x00400 RWE 0x4
  LOAD           0x0003f8 0x00100000 0x00000000 0x00a48 0x00a48 R E 0x4
  LOAD           0x000e40 0x00100a48 0x00000000 0x03130 0x03130 R E 0x4
  LOAD           0x003f70 0x00103b78 0x00000000 0x00ac4 0x00ac4 R E 0x4
  LOAD           0x004a34 0x21200000 0x00000000 0x00004 0x00004 RWE 0x4
  LOAD           0x000000 0x21200004 0x00000000 0x00000 0x01184 RWE 0x4
```

Problem occurs on section `.rodata`
It seems that there is an issue in the management of the SHT_NULL section `.sdata2`, before `.rodata`.

In the code below (https://github.com/serge1/ELFIO/blob/3e4a2fabfd0baed62af8ab18ddc1ac6c4be137df/elfio/elfio.hpp#L669)
```C
            // Special case:
            // Segments which start with the NULL section and have further sections
            else if ( seg->get_sections_num() > 1
                      && sections[seg->get_section_index_at( 0 )]->get_type() == SHT_NULL ) {
                seg_start_pos = 0;
                if ( seg->get_sections_num() ) {
                    segment_memory = segment_filesize = current_file_pos;
                }
            }
```
It seems that this code sets seg_start_pos to 0. Why?

Moreover, what is the use of `if ( seg->get_sections_num() )`,
inside the condition `if ( seg->get_sections_num() > 1` ?
Isn't it always true ?

I don't understand the pupose of this part of the code.
Any explaination/help would be great.

**Comment by belissent** [comment]
More info: I reverted back the code above to the code prior to
https://github.com/serge1/ELFIO/commit/91e61ec4b2f74f717c50d3a62b7b3348487f86ce#diff-c03eed55f6be5d7b996d7ddb85e1c57cR592
for the lines 592-595

And the ELF save worked...

**Comment by serge1** [comment]
I'll try to answer the question "It seems that this code sets seg_start_pos to 0. Why?" first.

ELFIO library makes an assumption that a segment is built of regular sections containing data. But, GNU linker produces a special case for Linux targets where a loadable segment also contains the "program header" which has no its own section. The code under the question tries to address this case. For example, it permits to load/save programs located in /usr/bin directory without known problem.

If you are observing that this code misbehaves for yet another scenario, would it be possible to submit such ELF way and a way to verify that it is still OK after the transforming.

Thank you,
Serge

**Comment by serge1** [comment]
> condition if ( seg->get_sections_num() > 1 ? Isn't it always true ?

**Comment by serge1** [comment]
There are segments that may contain no sections. For example STACK segment

**Comment by belissent** [comment]
> > condition if ( seg->get_sections_num() > 1 ? Isn't it always true ?> >

> There are segments that may contain no sections. For example STACK segment>

I was talking about the condition `if ( seg->get_sections_num() )`, which cannot be false, because inside the condition `if ( seg->get_sections_num() > 1 && ...`

**Comment by belissent** [comment]
Here is a test case reproducing the problem.
In the attached file: [reproduce issue 19.zip](https://github.com/serge1/ELFIO/files/4719433/reproduce.issue.19.zip)
  - The file `ELFIOTest1 - MODIFIED.cpp` contains a test case `null_section_inside_segment` that reproduces the issue.
  - The file `elfio - MODIFIED.hpp` contains the modification mentioned in a comment above (revert back the code above to the code prior to https://github.com/serge1/ELFIO/commit/91e61ec4b2f74f717c50d3a62b7b3348487f86ce#diff-c03eed55f6be5d7b996d7ddb85e1c57cR592).
With this modification, the test case that reproduces the problem passes (as well as all the others).

**Comment by serge1** [comment]
Thank you very much for sending out the test case. I have started to loot at it

**Comment by serge1** [comment]
Hi,
I have reviewed the change and it looks very reasonable. Don't you think that it worth to add a check on the section type anyhow?

**Comment by serge1** [comment]
Would you please submit the changes as a PR? I'll merge them.

**Comment by serge1** [comment]
Based on the recent conversation, the issue is closed. Please reopen in case similar case still persist
