### ISSUE TITLE
Rewriting the symbol table

### ISSUE THREAD

**Issue by BullyWiiPlaza** [serge1/ELFIO#45]
I want to use this library to rewrite the symbol table of an existing `ELF` file. In particular I would like to replace every function name with another one. The examples and documentation were very helpful to show me how to parse everything but it doesn't seem to explain how to "flush" changes back. The `symbol_section_accessor` does not have methods for writing, only `get_symbol`. Do I need to create a new `.symtab` and add all symbols I want into it? That seems pretty cumbersome and I'm not sure if the `ELF` will then still work seamlessly. In fact, getting the file offsets of the function names respectively would be enough as well but that also doesn't seem to be easily doable with `ELFIO`.

**Comment by serge1** [comment]
Hi,

I am not sure that what I am proposing is the best way to solve your problem, but here it goes anyway.

You may wish to look at the 'anonymizer' example of the ELFIO library.
https://github.com/serge1/ELFIO/blob/master/examples/anonymizer/anonymizer.cpp

The most recent version of the example renames a single function name in an executable ELF file. You may extend
this example according to your requirements.

Best regards,
Serge


________________________________

**Comment by BullyWiiPlaza** [comment]
Yeah, that looks good. Thank you 👍
