### ISSUE TITLE
Adding to vcpkg

### ISSUE THREAD

**Issue by schultetwin1** [serge1/ELFIO#53]
I have a fork of vcpkg (https://github.com/schultetwin1/vcpkg/tree/add_elfio_port) which will add elfio to vcpkg. If you're ok with it, I'd like open a pull request to merge elfio into vcpkg officially.

In order to do so, it would probably be better to wait for the next official release of ELFIO. So I'll wait for the next release and then put the pull request out.

**Comment by serge1** [comment]
There is no problem to produce the next official release. I'll do it today

**Comment by serge1** [comment]
The library official release 3.8 has been published

**Comment by schultetwin1** [comment]
Awesome! Thank you for the quick turn around!

PR is out microsoft/vcpkg#14314! I'll close this issue when it's complete

**Comment by schultetwin1** [comment]
Completed! microsoft/vcpkg/pull/14314

ELFIO is now on vcpkg.

**Comment by serge1** [comment]
Hi Matt,

Thank you very much! It is a huge achievement for the library.

I don't know vcpkg policies, but I didn't find 'examples' folder in 'share/elfio' directory of the distribution. Is it feasible to add it?

My dream is to find a maintainer for Debian distribution too. By a chance, do you know a ‘mentor’ who can do this?

Thank you,
Serge

**Comment by schultetwin1** [comment]
> I don't know vcpkg policies, but I didn't find 'examples' folder in 'share/elfio' directory of the distribution. Is it feasible to add it?

As mentioned in #56, normally vcpkg is only used for distributing the code needed to build, not for distributing examples. The [maintainer guidelines](https://vcpkg.readthedocs.io/en/latest/maintainers/maintainer-guide/#do-not-build-testsdocsexamples-by-default) for vcpkg also asks maintainers to not distribute examples (or tests).

> My dream is to find a maintainer for Debian distribution too. By a chance, do you know a ‘mentor’ who can do this?

I don't know too much about Debian distribution, but I do know we can have CMake create a .deb package (using `cpack` which comes with CMake). I can work on generating a .deb package as part of the build?

**Comment by serge1** [comment]
I have a private repository called ELFIOPackaging. The repository contains manual steps to produce .deb package. I think CMake can do it more professionally. So, yes, it would be great to have this generation as a part of the build

**Comment by serge1** [comment]
I have changed the visibility of the project to be ‘public’. You can see there what I have so far: [ELFIOPackaging](https://github.com/serge1/ELFIOPackaging)

**Comment by serge1** [comment]
> The maintainer guidelines for vcpkg also asks maintainers to not distribute examples (or tests).

**Comment by serge1** [comment]
> The maintainer guidelines for vcpkg also asks maintainers to not distribute examples (or tests).
I saw that they require not to build examples/tests. But, I think that it is OK to distribute them. Am I missing anything?

**Comment by serge1** [comment]
Sorry, it should be OK for the third time 8-(

> The maintainer guidelines for vcpkg also asks maintainers to not distribute examples (or tests).

I saw that they require not to build examples/tests. But, I think that it is OK to distribute them. Am I missing anything?

**Comment by serge1** [comment]
Hi Matt,

The Conan and Vcpkg started to appear at [Repology](https://repology.org/project/elfio/versions). Thanks again!
