### ISSUE TITLE
Elfio not on conan (yet) 

### ISSUE THREAD

**Issue by a4z** [serge1/ELFIO#56]
Since you need help with maintainers, @serge1 , and you are happy about  #53 ,  I added elfio to conan package manager, 

https://github.com/conan-io/conan-center-index/pull/3390

So I can at least contribute a bit back for using Elfio in a project. Its a wonderful library

Since you mentioned adding examples in #53: 
you do not add example folders into build dependencies.
C++ package mangers work in this respect a bit different than packages for a Linux distribution.
In case of vcpkg or conan you are just interested to get what you need to build your app, if more is needed you look to the sources.

As soon as the PR on conan is accepted, what should happen soon, this issue can be closed ;-)

**Comment by serge1** [comment]
Thank you very much! Things are getting better each day!

**Comment by serge1** [comment]
Hi Harald, it looks like the PR was finally accepted! I am sorry for the frustration there was on the way. Congratulations and Thank you very much!

**Comment by serge1** [comment]
Just FYI - the Conan and Vcpkg started to appear at [Repology](https://repology.org/project/elfio/versions)

**Comment by a4z** [comment]
There was not much frustration, I was just a bit stressed at the very moment, and due to the new community based review process, for some people the motivation too help is very high which can lead sometimes to more good tips than needed, but that is OK and better as the other way around.

And yes, the PR was accepted today, from now on it should be only keeping the DL up to date, something that theoretical could be automated with releases. 

did not now about repology.org, interesting site
Anyhow,  I think we can now close the PR, mission accomplished :-)
