### ISSUE TITLE
Cannot save to in-memory stream buffer

### ISSUE THREAD

**Issue by dmikushin** [serge1/ELFIO#67]
So strange that save() only works correctly with the output file, but not with an in-memory buffer. When I try to save elf into a stringstream, only first 64 bytes are written:

```
std::stringstream ss(std::ios::out);
e.save(ss);
std::string elf = ss.str(); // only first 64 bytes always!
```

Any clue?

**Comment by serge1** [comment]
int main( int argc, char** argv )
{
//    std::ofstream oss("test.out");
    std::stringstream oss("");
    oss << "Hello";
    std::cout <<  oss.tellp() << std::endl;
    oss.seekp(20);
    std::cout <<  oss.tellp() << std::endl;

    return 0;
}

**Comment by dmikushin** [comment]
Exactly!

```
% cat test.cpp
#include <iostream>
#include <sstream>

int main( int argc, char** argv )
{
	// std::ofstream oss("test.out");
	std::stringstream oss("");
	oss << "Hello";
	std::cout << oss.tellp() << std::endl;
	oss.seekp(20);
	std::cout << oss.tellp() << std::endl;

	return 0;
}

% g++ test.cpp -o ./test
% ./test                
5
-1
```

**Comment by dmikushin** [comment]
So maybe ELFIO should "preallocate" the underlying stream buffer by writing a placeholder buffer, whose size is already the size of the resulting ELF binary? Then seeks should become valid.

**Comment by serge1** [comment]
Please give a try to commit becd79d. It should fix the problem. Please let me know your results and close the issue in case of success

**Comment by serge1** [comment]
Please reopen if you still expirience a problem

**Comment by dmikushin** [comment]
Yes, it works now! Many thanks for your support!
