### ISSUE TITLE
Explicit = Operator for elfio Segfault

### ISSUE THREAD

**Issue by foreverska** [serge1/ELFIO#68]
Correct me if I'm wrong but ELFIO::elfio seems to have an explicit = operator which does a shallow copy of pointers within the object.  This causes a segfault on second deconstruction if you happen to use it.

It should probably be explicitly deleted, a deep copy implemented or a solution which can survive a shallow copy (thread safety + shared pointers).

**Comment by serge1** [comment]
Thank you for mentioning this. Indeed, the copy constructor and assignment operator are not supported.
I have added their deletion in commit 29114f65.

Please let me know your results.

**Comment by pavelkryukov** [comment]
I propose following [Rule of Five](https://en.wikipedia.org/wiki/Rule_of_three_(C%2B%2B_programming)) to the end and define move ctor and assignment operator, at least with `= default;` syntax.

**Comment by serge1** [comment]
Hi @pavelkryukov, thank you for the advice. The move constructor and assignment are implemented in f591a3b7.
Just to make sure - is this what you meant?

**Comment by pavelkryukov** [comment]
Yes, looks great.

**Comment by serge1** [comment]
Please reopen if you feel that the issue still persists
