### ISSUE TITLE
Is the elfhash algorithm outdated? 

### ISSUE THREAD

**Issue by Hackerl** [serge1/ELFIO#72]
Searching the symbol table by name seems to fail, because ".gnu.hash" uses the DJB (Daniel J Bernstein) hash algorithm.
https://github.com/serge1/ELFIO/blob/master/elfio/elfio_utils.hpp#L165

**Comment by serge1** [comment]
Thank you for pointing me to this!

**Comment by serge1** [comment]
Support for the GNU hash algorithm has been added in commit ef26228
