### ISSUE TITLE
64 bit writer example:  ELF load command alignment not page-aligned

### ISSUE THREAD

**Issue by rimmartin** [serge1/ELFIO#8]
Hi,

I tried https://github.com/serge1/ELFIO/blob/master/examples/writer/writer.cpp with changes to make it 64 bit, save to .so and dlopen it. Get the error: ELF load command alignment not page-aligned

https://github.com/serge1/ELFIO/blob/master/examples/writer/writer.cpp#L10 to:
```
    writer.create( ELFCLASS64, ELFDATA2LSB );

    writer.set_os_abi( ELFOSABI_LINUX );
    writer.set_type( ET_DYN );
    writer.set_machine( EM_X86_64 );

...
    // Create ELF file
    writer.save( "./tests/examples/libxml.so" );
    int* handle=(int*)dlopen("./tests/examples/libxml.so", RTLD_LAZY);
    if (!handle) {
        std::cerr << "Cannot open library: " << dlerror() << '\n';
    }
    else dlclose(handle);

```
Searching the interwebs doesn't turn up what it means.  Is there something else I need to change?

**Comment by serge1** [comment]
Hi,

It is not enough to set ET_DYN type of ELF file to make it shared object suitable for loading. There are other segment/sections that are expected by loader be a part of ELF file. For example, .dynamic, .dynsym section and DYNAMIC segment are supposed to be added.

Best regards,
Serge
