### ISSUE TITLE
Read only required section information in the elfio class 'load' function 

### ISSUE THREAD

**Issue by oss-explorer** [serge1/ELFIO#80]
Can only the required sections of the executable be read into the memory instead of reading the complete binary/all the sections and segments of the binary in the 'class elfio' load() function?
With the complete executable being read into the memory, there is a peak in memory usage when binary sizes are in GB.
Can you please consider this enhancement?

**Comment by serge1** [comment]
Thank you for your suggestion.
The current design of the library based on the fact that lifetime of the file stream cannot be garanteed after `elfio::load()` function finishes.
I'll see whether a lazy section/segment data loading is possible as far as user garantees proper lifetime of the stream.

**Comment by Meiri28** [comment]
beside the peak in the memory, there is another reason to take this approach. some of linux distribution have live memory dump file in `/proc/kcore`, in this elf file you can't always read from all of his segments(some of them are not readable although the file is with read permissions). this scenario lead to error in the stream and later to mistakes in the data elfio parse from this file.

**Comment by serge1** [comment]
Hi @Meiri28, it is interesting aspect. How do you urge the library to treat /proc/kcore being an ELF file?

**Comment by Meiri28** [comment]
This file is in elf formate. It's looks like a core dump but his size is enormous and as I said not all the data is readable. You can read more about kcore file in [here](https://schlafwandler.github.io/posts/dumping-/proc/kcore/).

**Comment by serge1** [comment]
The commit 9827eac9 implementing 'lazy' load for segments and sections should finalize the initial request. Please reopen the issue if it does not work for you
