### ISSUE TITLE
Adding PROGBITS section

### ISSUE THREAD

**Issue by dsnezhkov** [serge1/ELFIO#86]
Hi,

Is there an API to add an arbitrary PROGBITS section. I see the API can do notes, dynamic and strings types. For example, is it possible to create a section and add raw data buffer to the section without structured layout?

I am working off of the add_note example:
```
 note_sec->set_type( SHT_PROGBITS);
.. What is the correct accessor writer for this ? 
 note_writer.add_XXXX( &data_buffer, size );
```
thank you.

**Comment by serge1** [comment]
Hi,
An arbitrary PROGBITS section can be added by using 'section' API. Unstructured data can be set by added by set_data(). No  special section accessor is required for this case.
See "ELF File Writer" example in the documentation. The text and data sections are added without accessors.

Does it answer your question?

**Comment by dsnezhkov** [comment]
Perfect, Thank you!
