### ISSUE TITLE
When will the next stable version be released?

### ISSUE THREAD

**Issue by Hackerl** [serge1/ELFIO#87]
I want to use the new features, but I don't know which commit is relatively stable after v3.9.

**Comment by serge1** [comment]
I am going to finish 'symbol version' section accessor soon. The official release will be produced afterwards.
In case you are looking for a just stable commit, you may take any recent one - I am trying to keep API stable and the core routines were not changed recently.

**Comment by Hackerl** [comment]
thank you for your reply.
