### ISSUE TITLE
mmap instead of streams

### ISSUE THREAD

**Issue by klueska** [serge1/ELFIO#9]
Have you ever considered using mmap under the hood to avoid steaming the entire ELF file into memory at load time?

**Comment by serge1** [comment]
Hi klueska,
There are people who uses streaming for 'remote' access to the file. So, it is preferable to leave it.

Also, mmap is OS dependent function, so I don't think it worth to substitute streaming with it. But, as an additional execution path it might be acceptable. (A contribution is welcomed!). Do you expect a huge performance gain when using this mechanism?

**Comment by klueska** [comment]
The benefits come when you have a HUGE binary you are tyring to parse. This
is particularly important when you consider some large statically linked
binaries which can be GB in size. Using something like mmap lets you pull
the file into your virtual address space without actually reading all the
bytes from disk until you actually touch the pages where those bytes live.

For now our usage of ELFIO shouldn't be impacted by this too much, but if
it becomes a problem in the future, I may get back to you about that
contribution :)
