### ISSUE TITLE
Compilation error if including after <Windows.h>

### ISSUE THREAD

**Issue by ThirteenAG** [serge1/ELFIO#95]
Hey, wondering if something can be done about that, this piece of code compiles fine:
```
#include <elfio/elfio.hpp>
#include <Windows.h>

void test()
{
}
```

But this one doesn't:
```
#include <Windows.h>
#include <elfio/elfio.hpp>

void test()
{
}
```

```
elfio_section.hpp(214,59): warning C4003: not enough arguments for function-like macro invocation 'max'
elfio_section.hpp(214,59): error C2589: '(': illegal token on right side of '::'
```

![image](https://user-images.githubusercontent.com/4904157/164197824-20679e73-2be5-4147-ad11-0700ca38c70b.png)

**Comment by serge1** [comment]
Hi,
The question is not directly related to the ELFIO library. Anyway, to prevent Windows.h min/max macros, you may use
`#define NOMINMAX`
definition prior including the header file
